// Code generated by "enumer -type=AttrCode -trimprefix ATTR_"; DO NOT EDIT.

package msg

import (
	"fmt"
	"strings"
)

const (
	_AttrCodeName_0      = "UNSPECIFIEDORIGINASPATHNEXTHOPMEDLOCALPREFAGGREGATEAGGREGATORCOMMUNITYORIGINATORCLUSTER_LIST"
	_AttrCodeLowerName_0 = "unspecifiedoriginaspathnexthopmedlocalprefaggregateaggregatorcommunityoriginatorcluster_list"
	_AttrCodeName_1      = "MP_REACHMP_UNREACHEXT_COMMUNITYAS4PATHAS4AGGREGATOR"
	_AttrCodeLowerName_1 = "mp_reachmp_unreachext_communityas4pathas4aggregator"
	_AttrCodeName_2      = "PMSI_TUNNELTUNNELTRAFFIC_ENGIPV6_EXT_COMMUNITYAIGPPE_DISTING"
	_AttrCodeLowerName_2 = "pmsi_tunneltunneltraffic_engipv6_ext_communityaigppe_disting"
	_AttrCodeName_3      = "BGP_LS"
	_AttrCodeLowerName_3 = "bgp_ls"
	_AttrCodeName_4      = "LARGE_COMMUNITYBGPSEC_PATH"
	_AttrCodeLowerName_4 = "large_communitybgpsec_path"
	_AttrCodeName_5      = "OTCDPATHSFP_ATTRBFD_DISCRIMINATORRCAPREFIX_SID"
	_AttrCodeLowerName_5 = "otcdpathsfp_attrbfd_discriminatorrcaprefix_sid"
	_AttrCodeName_6      = "SET"
	_AttrCodeLowerName_6 = "set"
)

var (
	_AttrCodeIndex_0 = [...]uint8{0, 11, 17, 23, 30, 33, 42, 51, 61, 70, 80, 92}
	_AttrCodeIndex_1 = [...]uint8{0, 8, 18, 31, 38, 51}
	_AttrCodeIndex_2 = [...]uint8{0, 11, 17, 28, 46, 50, 60}
	_AttrCodeIndex_3 = [...]uint8{0, 6}
	_AttrCodeIndex_4 = [...]uint8{0, 15, 26}
	_AttrCodeIndex_5 = [...]uint8{0, 3, 8, 16, 33, 36, 46}
	_AttrCodeIndex_6 = [...]uint8{0, 3}
)

func (i AttrCode) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _AttrCodeName_0[_AttrCodeIndex_0[i]:_AttrCodeIndex_0[i+1]]
	case 14 <= i && i <= 18:
		i -= 14
		return _AttrCodeName_1[_AttrCodeIndex_1[i]:_AttrCodeIndex_1[i+1]]
	case 22 <= i && i <= 27:
		i -= 22
		return _AttrCodeName_2[_AttrCodeIndex_2[i]:_AttrCodeIndex_2[i+1]]
	case i == 29:
		return _AttrCodeName_3
	case 32 <= i && i <= 33:
		i -= 32
		return _AttrCodeName_4[_AttrCodeIndex_4[i]:_AttrCodeIndex_4[i+1]]
	case 35 <= i && i <= 40:
		i -= 35
		return _AttrCodeName_5[_AttrCodeIndex_5[i]:_AttrCodeIndex_5[i+1]]
	case i == 128:
		return _AttrCodeName_6
	default:
		return fmt.Sprintf("AttrCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AttrCodeNoOp() {
	var x [1]struct{}
	_ = x[ATTR_UNSPECIFIED-(0)]
	_ = x[ATTR_ORIGIN-(1)]
	_ = x[ATTR_ASPATH-(2)]
	_ = x[ATTR_NEXTHOP-(3)]
	_ = x[ATTR_MED-(4)]
	_ = x[ATTR_LOCALPREF-(5)]
	_ = x[ATTR_AGGREGATE-(6)]
	_ = x[ATTR_AGGREGATOR-(7)]
	_ = x[ATTR_COMMUNITY-(8)]
	_ = x[ATTR_ORIGINATOR-(9)]
	_ = x[ATTR_CLUSTER_LIST-(10)]
	_ = x[ATTR_MP_REACH-(14)]
	_ = x[ATTR_MP_UNREACH-(15)]
	_ = x[ATTR_EXT_COMMUNITY-(16)]
	_ = x[ATTR_AS4PATH-(17)]
	_ = x[ATTR_AS4AGGREGATOR-(18)]
	_ = x[ATTR_PMSI_TUNNEL-(22)]
	_ = x[ATTR_TUNNEL-(23)]
	_ = x[ATTR_TRAFFIC_ENG-(24)]
	_ = x[ATTR_IPV6_EXT_COMMUNITY-(25)]
	_ = x[ATTR_AIGP-(26)]
	_ = x[ATTR_PE_DISTING-(27)]
	_ = x[ATTR_BGP_LS-(29)]
	_ = x[ATTR_LARGE_COMMUNITY-(32)]
	_ = x[ATTR_BGPSEC_PATH-(33)]
	_ = x[ATTR_OTC-(35)]
	_ = x[ATTR_DPATH-(36)]
	_ = x[ATTR_SFP_ATTR-(37)]
	_ = x[ATTR_BFD_DISCRIMINATOR-(38)]
	_ = x[ATTR_RCA-(39)]
	_ = x[ATTR_PREFIX_SID-(40)]
	_ = x[ATTR_SET-(128)]
}

var _AttrCodeValues = []AttrCode{ATTR_UNSPECIFIED, ATTR_ORIGIN, ATTR_ASPATH, ATTR_NEXTHOP, ATTR_MED, ATTR_LOCALPREF, ATTR_AGGREGATE, ATTR_AGGREGATOR, ATTR_COMMUNITY, ATTR_ORIGINATOR, ATTR_CLUSTER_LIST, ATTR_MP_REACH, ATTR_MP_UNREACH, ATTR_EXT_COMMUNITY, ATTR_AS4PATH, ATTR_AS4AGGREGATOR, ATTR_PMSI_TUNNEL, ATTR_TUNNEL, ATTR_TRAFFIC_ENG, ATTR_IPV6_EXT_COMMUNITY, ATTR_AIGP, ATTR_PE_DISTING, ATTR_BGP_LS, ATTR_LARGE_COMMUNITY, ATTR_BGPSEC_PATH, ATTR_OTC, ATTR_DPATH, ATTR_SFP_ATTR, ATTR_BFD_DISCRIMINATOR, ATTR_RCA, ATTR_PREFIX_SID, ATTR_SET}

var _AttrCodeNameToValueMap = map[string]AttrCode{
	_AttrCodeName_0[0:11]:       ATTR_UNSPECIFIED,
	_AttrCodeLowerName_0[0:11]:  ATTR_UNSPECIFIED,
	_AttrCodeName_0[11:17]:      ATTR_ORIGIN,
	_AttrCodeLowerName_0[11:17]: ATTR_ORIGIN,
	_AttrCodeName_0[17:23]:      ATTR_ASPATH,
	_AttrCodeLowerName_0[17:23]: ATTR_ASPATH,
	_AttrCodeName_0[23:30]:      ATTR_NEXTHOP,
	_AttrCodeLowerName_0[23:30]: ATTR_NEXTHOP,
	_AttrCodeName_0[30:33]:      ATTR_MED,
	_AttrCodeLowerName_0[30:33]: ATTR_MED,
	_AttrCodeName_0[33:42]:      ATTR_LOCALPREF,
	_AttrCodeLowerName_0[33:42]: ATTR_LOCALPREF,
	_AttrCodeName_0[42:51]:      ATTR_AGGREGATE,
	_AttrCodeLowerName_0[42:51]: ATTR_AGGREGATE,
	_AttrCodeName_0[51:61]:      ATTR_AGGREGATOR,
	_AttrCodeLowerName_0[51:61]: ATTR_AGGREGATOR,
	_AttrCodeName_0[61:70]:      ATTR_COMMUNITY,
	_AttrCodeLowerName_0[61:70]: ATTR_COMMUNITY,
	_AttrCodeName_0[70:80]:      ATTR_ORIGINATOR,
	_AttrCodeLowerName_0[70:80]: ATTR_ORIGINATOR,
	_AttrCodeName_0[80:92]:      ATTR_CLUSTER_LIST,
	_AttrCodeLowerName_0[80:92]: ATTR_CLUSTER_LIST,
	_AttrCodeName_1[0:8]:        ATTR_MP_REACH,
	_AttrCodeLowerName_1[0:8]:   ATTR_MP_REACH,
	_AttrCodeName_1[8:18]:       ATTR_MP_UNREACH,
	_AttrCodeLowerName_1[8:18]:  ATTR_MP_UNREACH,
	_AttrCodeName_1[18:31]:      ATTR_EXT_COMMUNITY,
	_AttrCodeLowerName_1[18:31]: ATTR_EXT_COMMUNITY,
	_AttrCodeName_1[31:38]:      ATTR_AS4PATH,
	_AttrCodeLowerName_1[31:38]: ATTR_AS4PATH,
	_AttrCodeName_1[38:51]:      ATTR_AS4AGGREGATOR,
	_AttrCodeLowerName_1[38:51]: ATTR_AS4AGGREGATOR,
	_AttrCodeName_2[0:11]:       ATTR_PMSI_TUNNEL,
	_AttrCodeLowerName_2[0:11]:  ATTR_PMSI_TUNNEL,
	_AttrCodeName_2[11:17]:      ATTR_TUNNEL,
	_AttrCodeLowerName_2[11:17]: ATTR_TUNNEL,
	_AttrCodeName_2[17:28]:      ATTR_TRAFFIC_ENG,
	_AttrCodeLowerName_2[17:28]: ATTR_TRAFFIC_ENG,
	_AttrCodeName_2[28:46]:      ATTR_IPV6_EXT_COMMUNITY,
	_AttrCodeLowerName_2[28:46]: ATTR_IPV6_EXT_COMMUNITY,
	_AttrCodeName_2[46:50]:      ATTR_AIGP,
	_AttrCodeLowerName_2[46:50]: ATTR_AIGP,
	_AttrCodeName_2[50:60]:      ATTR_PE_DISTING,
	_AttrCodeLowerName_2[50:60]: ATTR_PE_DISTING,
	_AttrCodeName_3[0:6]:        ATTR_BGP_LS,
	_AttrCodeLowerName_3[0:6]:   ATTR_BGP_LS,
	_AttrCodeName_4[0:15]:       ATTR_LARGE_COMMUNITY,
	_AttrCodeLowerName_4[0:15]:  ATTR_LARGE_COMMUNITY,
	_AttrCodeName_4[15:26]:      ATTR_BGPSEC_PATH,
	_AttrCodeLowerName_4[15:26]: ATTR_BGPSEC_PATH,
	_AttrCodeName_5[0:3]:        ATTR_OTC,
	_AttrCodeLowerName_5[0:3]:   ATTR_OTC,
	_AttrCodeName_5[3:8]:        ATTR_DPATH,
	_AttrCodeLowerName_5[3:8]:   ATTR_DPATH,
	_AttrCodeName_5[8:16]:       ATTR_SFP_ATTR,
	_AttrCodeLowerName_5[8:16]:  ATTR_SFP_ATTR,
	_AttrCodeName_5[16:33]:      ATTR_BFD_DISCRIMINATOR,
	_AttrCodeLowerName_5[16:33]: ATTR_BFD_DISCRIMINATOR,
	_AttrCodeName_5[33:36]:      ATTR_RCA,
	_AttrCodeLowerName_5[33:36]: ATTR_RCA,
	_AttrCodeName_5[36:46]:      ATTR_PREFIX_SID,
	_AttrCodeLowerName_5[36:46]: ATTR_PREFIX_SID,
	_AttrCodeName_6[0:3]:        ATTR_SET,
	_AttrCodeLowerName_6[0:3]:   ATTR_SET,
}

var _AttrCodeNames = []string{
	_AttrCodeName_0[0:11],
	_AttrCodeName_0[11:17],
	_AttrCodeName_0[17:23],
	_AttrCodeName_0[23:30],
	_AttrCodeName_0[30:33],
	_AttrCodeName_0[33:42],
	_AttrCodeName_0[42:51],
	_AttrCodeName_0[51:61],
	_AttrCodeName_0[61:70],
	_AttrCodeName_0[70:80],
	_AttrCodeName_0[80:92],
	_AttrCodeName_1[0:8],
	_AttrCodeName_1[8:18],
	_AttrCodeName_1[18:31],
	_AttrCodeName_1[31:38],
	_AttrCodeName_1[38:51],
	_AttrCodeName_2[0:11],
	_AttrCodeName_2[11:17],
	_AttrCodeName_2[17:28],
	_AttrCodeName_2[28:46],
	_AttrCodeName_2[46:50],
	_AttrCodeName_2[50:60],
	_AttrCodeName_3[0:6],
	_AttrCodeName_4[0:15],
	_AttrCodeName_4[15:26],
	_AttrCodeName_5[0:3],
	_AttrCodeName_5[3:8],
	_AttrCodeName_5[8:16],
	_AttrCodeName_5[16:33],
	_AttrCodeName_5[33:36],
	_AttrCodeName_5[36:46],
	_AttrCodeName_6[0:3],
}

// AttrCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AttrCodeString(s string) (AttrCode, error) {
	if val, ok := _AttrCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AttrCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AttrCode values", s)
}

// AttrCodeValues returns all values of the enum
func AttrCodeValues() []AttrCode {
	return _AttrCodeValues
}

// AttrCodeStrings returns a slice of all String values of the enum
func AttrCodeStrings() []string {
	strs := make([]string, len(_AttrCodeNames))
	copy(strs, _AttrCodeNames)
	return strs
}

// IsAAttrCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AttrCode) IsAAttrCode() bool {
	for _, v := range _AttrCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
