// Code generated by "enumer -type=CapCode -trimprefix CAP_"; DO NOT EDIT.

package msg

import (
	"fmt"
	"strings"
)

const (
	_CapCodeName_0      = "UNSPECIFIEDMPROUTE_REFRESHOUTBOUND_FILTERING"
	_CapCodeLowerName_0 = "unspecifiedmproute_refreshoutbound_filtering"
	_CapCodeName_1      = "EXTENDED_NEXTHOPEXTENDED_MESSAGEBGPSECMULTIPLE_LABELSROLE"
	_CapCodeLowerName_1 = "extended_nexthopextended_messagebgpsecmultiple_labelsrole"
	_CapCodeName_2      = "GRACEFUL_RESTARTAS4"
	_CapCodeLowerName_2 = "graceful_restartas4"
	_CapCodeName_3      = "DYNAMICMULTISESSIONADDPATHENHANCED_ROUTE_REFRESHLLGRROUTING_POLICYFQDNBFDVERSION"
	_CapCodeLowerName_3 = "dynamicmultisessionaddpathenhanced_route_refreshllgrrouting_policyfqdnbfdversion"
	_CapCodeName_4      = "PRE_ROUTE_REFRESH"
	_CapCodeLowerName_4 = "pre_route_refresh"
)

var (
	_CapCodeIndex_0 = [...]uint8{0, 11, 13, 26, 44}
	_CapCodeIndex_1 = [...]uint8{0, 16, 32, 38, 53, 57}
	_CapCodeIndex_2 = [...]uint8{0, 16, 19}
	_CapCodeIndex_3 = [...]uint8{0, 7, 19, 26, 48, 52, 66, 70, 73, 80}
	_CapCodeIndex_4 = [...]uint8{0, 17}
)

func (i CapCode) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CapCodeName_0[_CapCodeIndex_0[i]:_CapCodeIndex_0[i+1]]
	case 5 <= i && i <= 9:
		i -= 5
		return _CapCodeName_1[_CapCodeIndex_1[i]:_CapCodeIndex_1[i+1]]
	case 64 <= i && i <= 65:
		i -= 64
		return _CapCodeName_2[_CapCodeIndex_2[i]:_CapCodeIndex_2[i+1]]
	case 67 <= i && i <= 75:
		i -= 67
		return _CapCodeName_3[_CapCodeIndex_3[i]:_CapCodeIndex_3[i+1]]
	case i == 128:
		return _CapCodeName_4
	default:
		return fmt.Sprintf("CapCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CapCodeNoOp() {
	var x [1]struct{}
	_ = x[CAP_UNSPECIFIED-(0)]
	_ = x[CAP_MP-(1)]
	_ = x[CAP_ROUTE_REFRESH-(2)]
	_ = x[CAP_OUTBOUND_FILTERING-(3)]
	_ = x[CAP_EXTENDED_NEXTHOP-(5)]
	_ = x[CAP_EXTENDED_MESSAGE-(6)]
	_ = x[CAP_BGPSEC-(7)]
	_ = x[CAP_MULTIPLE_LABELS-(8)]
	_ = x[CAP_ROLE-(9)]
	_ = x[CAP_GRACEFUL_RESTART-(64)]
	_ = x[CAP_AS4-(65)]
	_ = x[CAP_DYNAMIC-(67)]
	_ = x[CAP_MULTISESSION-(68)]
	_ = x[CAP_ADDPATH-(69)]
	_ = x[CAP_ENHANCED_ROUTE_REFRESH-(70)]
	_ = x[CAP_LLGR-(71)]
	_ = x[CAP_ROUTING_POLICY-(72)]
	_ = x[CAP_FQDN-(73)]
	_ = x[CAP_BFD-(74)]
	_ = x[CAP_VERSION-(75)]
	_ = x[CAP_PRE_ROUTE_REFRESH-(128)]
}

var _CapCodeValues = []CapCode{CAP_UNSPECIFIED, CAP_MP, CAP_ROUTE_REFRESH, CAP_OUTBOUND_FILTERING, CAP_EXTENDED_NEXTHOP, CAP_EXTENDED_MESSAGE, CAP_BGPSEC, CAP_MULTIPLE_LABELS, CAP_ROLE, CAP_GRACEFUL_RESTART, CAP_AS4, CAP_DYNAMIC, CAP_MULTISESSION, CAP_ADDPATH, CAP_ENHANCED_ROUTE_REFRESH, CAP_LLGR, CAP_ROUTING_POLICY, CAP_FQDN, CAP_BFD, CAP_VERSION, CAP_PRE_ROUTE_REFRESH}

var _CapCodeNameToValueMap = map[string]CapCode{
	_CapCodeName_0[0:11]:       CAP_UNSPECIFIED,
	_CapCodeLowerName_0[0:11]:  CAP_UNSPECIFIED,
	_CapCodeName_0[11:13]:      CAP_MP,
	_CapCodeLowerName_0[11:13]: CAP_MP,
	_CapCodeName_0[13:26]:      CAP_ROUTE_REFRESH,
	_CapCodeLowerName_0[13:26]: CAP_ROUTE_REFRESH,
	_CapCodeName_0[26:44]:      CAP_OUTBOUND_FILTERING,
	_CapCodeLowerName_0[26:44]: CAP_OUTBOUND_FILTERING,
	_CapCodeName_1[0:16]:       CAP_EXTENDED_NEXTHOP,
	_CapCodeLowerName_1[0:16]:  CAP_EXTENDED_NEXTHOP,
	_CapCodeName_1[16:32]:      CAP_EXTENDED_MESSAGE,
	_CapCodeLowerName_1[16:32]: CAP_EXTENDED_MESSAGE,
	_CapCodeName_1[32:38]:      CAP_BGPSEC,
	_CapCodeLowerName_1[32:38]: CAP_BGPSEC,
	_CapCodeName_1[38:53]:      CAP_MULTIPLE_LABELS,
	_CapCodeLowerName_1[38:53]: CAP_MULTIPLE_LABELS,
	_CapCodeName_1[53:57]:      CAP_ROLE,
	_CapCodeLowerName_1[53:57]: CAP_ROLE,
	_CapCodeName_2[0:16]:       CAP_GRACEFUL_RESTART,
	_CapCodeLowerName_2[0:16]:  CAP_GRACEFUL_RESTART,
	_CapCodeName_2[16:19]:      CAP_AS4,
	_CapCodeLowerName_2[16:19]: CAP_AS4,
	_CapCodeName_3[0:7]:        CAP_DYNAMIC,
	_CapCodeLowerName_3[0:7]:   CAP_DYNAMIC,
	_CapCodeName_3[7:19]:       CAP_MULTISESSION,
	_CapCodeLowerName_3[7:19]:  CAP_MULTISESSION,
	_CapCodeName_3[19:26]:      CAP_ADDPATH,
	_CapCodeLowerName_3[19:26]: CAP_ADDPATH,
	_CapCodeName_3[26:48]:      CAP_ENHANCED_ROUTE_REFRESH,
	_CapCodeLowerName_3[26:48]: CAP_ENHANCED_ROUTE_REFRESH,
	_CapCodeName_3[48:52]:      CAP_LLGR,
	_CapCodeLowerName_3[48:52]: CAP_LLGR,
	_CapCodeName_3[52:66]:      CAP_ROUTING_POLICY,
	_CapCodeLowerName_3[52:66]: CAP_ROUTING_POLICY,
	_CapCodeName_3[66:70]:      CAP_FQDN,
	_CapCodeLowerName_3[66:70]: CAP_FQDN,
	_CapCodeName_3[70:73]:      CAP_BFD,
	_CapCodeLowerName_3[70:73]: CAP_BFD,
	_CapCodeName_3[73:80]:      CAP_VERSION,
	_CapCodeLowerName_3[73:80]: CAP_VERSION,
	_CapCodeName_4[0:17]:       CAP_PRE_ROUTE_REFRESH,
	_CapCodeLowerName_4[0:17]:  CAP_PRE_ROUTE_REFRESH,
}

var _CapCodeNames = []string{
	_CapCodeName_0[0:11],
	_CapCodeName_0[11:13],
	_CapCodeName_0[13:26],
	_CapCodeName_0[26:44],
	_CapCodeName_1[0:16],
	_CapCodeName_1[16:32],
	_CapCodeName_1[32:38],
	_CapCodeName_1[38:53],
	_CapCodeName_1[53:57],
	_CapCodeName_2[0:16],
	_CapCodeName_2[16:19],
	_CapCodeName_3[0:7],
	_CapCodeName_3[7:19],
	_CapCodeName_3[19:26],
	_CapCodeName_3[26:48],
	_CapCodeName_3[48:52],
	_CapCodeName_3[52:66],
	_CapCodeName_3[66:70],
	_CapCodeName_3[70:73],
	_CapCodeName_3[73:80],
	_CapCodeName_4[0:17],
}

// CapCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CapCodeString(s string) (CapCode, error) {
	if val, ok := _CapCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CapCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CapCode values", s)
}

// CapCodeValues returns all values of the enum
func CapCodeValues() []CapCode {
	return _CapCodeValues
}

// CapCodeStrings returns a slice of all String values of the enum
func CapCodeStrings() []string {
	strs := make([]string, len(_CapCodeNames))
	copy(strs, _CapCodeNames)
	return strs
}

// IsACapCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CapCode) IsACapCode() bool {
	for _, v := range _CapCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
