// Code generated by "enumer -type Dir -trimprefix DIR_"; DO NOT EDIT.

package msg

import (
	"fmt"
	"strings"
)

const _DirName = "LRLR"

var _DirIndex = [...]uint8{0, 1, 2, 4}

const _DirLowerName = "lrlr"

func (i Dir) String() string {
	i -= 1
	if i >= Dir(len(_DirIndex)-1) {
		return fmt.Sprintf("Dir(%d)", i+1)
	}
	return _DirName[_DirIndex[i]:_DirIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DirNoOp() {
	var x [1]struct{}
	_ = x[DIR_L-(1)]
	_ = x[DIR_R-(2)]
	_ = x[DIR_LR-(3)]
}

var _DirValues = []Dir{DIR_L, DIR_R, DIR_LR}

var _DirNameToValueMap = map[string]Dir{
	_DirName[0:1]:      DIR_L,
	_DirLowerName[0:1]: DIR_L,
	_DirName[1:2]:      DIR_R,
	_DirLowerName[1:2]: DIR_R,
	_DirName[2:4]:      DIR_LR,
	_DirLowerName[2:4]: DIR_LR,
}

var _DirNames = []string{
	_DirName[0:1],
	_DirName[1:2],
	_DirName[2:4],
}

// DirString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DirString(s string) (Dir, error) {
	if val, ok := _DirNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DirNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Dir values", s)
}

// DirValues returns all values of the enum
func DirValues() []Dir {
	return _DirValues
}

// DirStrings returns a slice of all String values of the enum
func DirStrings() []string {
	strs := make([]string, len(_DirNames))
	copy(strs, _DirNames)
	return strs
}

// IsADir returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Dir) IsADir() bool {
	for _, v := range _DirValues {
		if i == v {
			return true
		}
	}
	return false
}
