// Code generated by "enumer -type Safi -trimprefix SAFI_"; DO NOT EDIT.

package msg

import (
	"fmt"
	"strings"
)

const (
	_SafiName_0      = "UNICASTMULTICAST"
	_SafiLowerName_0 = "unicastmulticast"
	_SafiName_1      = "MPLSMCAST_VPNPLACEMENT_MSPW"
	_SafiLowerName_1 = "mplsmcast_vpnplacement_mspw"
	_SafiName_2      = "MCAST_VPLSSFC"
	_SafiLowerName_2 = "mcast_vplssfc"
	_SafiName_3      = "TUNNELVPLSMDT4OVER66OVER4L1VPN_DISCOVERYEVPNSLSLS_VPNSR_TE_POLICYSD_WAN_CAPABILITIESROUTING_POLICYCLASSFUL_TRANSPORTTUNNELED_FLOWSPECMCAST_TREEDPSLS_SPF"
	_SafiLowerName_3 = "tunnelvplsmdt4over66over4l1vpn_discoveryevpnslsls_vpnsr_te_policysd_wan_capabilitiesrouting_policyclassful_transporttunneled_flowspecmcast_treedpsls_spf"
	_SafiName_4      = "CARVPN_CARMUP"
	_SafiLowerName_4 = "carvpn_carmup"
	_SafiName_5      = "MPLS_VPNMULTICAST_VPNS"
	_SafiLowerName_5 = "mpls_vpnmulticast_vpns"
	_SafiName_6      = "ROUTE_TARGETFLOWSPECL3VPN_FLOWSPEC"
	_SafiLowerName_6 = "route_targetflowspecl3vpn_flowspec"
	_SafiName_7      = "VPN_DISCOVERY"
	_SafiLowerName_7 = "vpn_discovery"
)

var (
	_SafiIndex_0 = [...]uint8{0, 7, 16}
	_SafiIndex_1 = [...]uint8{0, 4, 13, 27}
	_SafiIndex_2 = [...]uint8{0, 10, 13}
	_SafiIndex_3 = [...]uint8{0, 6, 10, 13, 19, 25, 40, 45, 47, 53, 65, 84, 98, 116, 133, 143, 146, 152}
	_SafiIndex_4 = [...]uint8{0, 3, 10, 13}
	_SafiIndex_5 = [...]uint8{0, 8, 22}
	_SafiIndex_6 = [...]uint8{0, 12, 20, 34}
	_SafiIndex_7 = [...]uint8{0, 13}
)

func (i Safi) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _SafiName_0[_SafiIndex_0[i]:_SafiIndex_0[i+1]]
	case 4 <= i && i <= 6:
		i -= 4
		return _SafiName_1[_SafiIndex_1[i]:_SafiIndex_1[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _SafiName_2[_SafiIndex_2[i]:_SafiIndex_2[i+1]]
	case 64 <= i && i <= 80:
		i -= 64
		return _SafiName_3[_SafiIndex_3[i]:_SafiIndex_3[i+1]]
	case 83 <= i && i <= 85:
		i -= 83
		return _SafiName_4[_SafiIndex_4[i]:_SafiIndex_4[i+1]]
	case 128 <= i && i <= 129:
		i -= 128
		return _SafiName_5[_SafiIndex_5[i]:_SafiIndex_5[i+1]]
	case 132 <= i && i <= 134:
		i -= 132
		return _SafiName_6[_SafiIndex_6[i]:_SafiIndex_6[i+1]]
	case i == 140:
		return _SafiName_7
	default:
		return fmt.Sprintf("Safi(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SafiNoOp() {
	var x [1]struct{}
	_ = x[SAFI_UNICAST-(1)]
	_ = x[SAFI_MULTICAST-(2)]
	_ = x[SAFI_MPLS-(4)]
	_ = x[SAFI_MCAST_VPN-(5)]
	_ = x[SAFI_PLACEMENT_MSPW-(6)]
	_ = x[SAFI_MCAST_VPLS-(8)]
	_ = x[SAFI_SFC-(9)]
	_ = x[SAFI_TUNNEL-(64)]
	_ = x[SAFI_VPLS-(65)]
	_ = x[SAFI_MDT-(66)]
	_ = x[SAFI_4OVER6-(67)]
	_ = x[SAFI_6OVER4-(68)]
	_ = x[SAFI_L1VPN_DISCOVERY-(69)]
	_ = x[SAFI_EVPNS-(70)]
	_ = x[SAFI_LS-(71)]
	_ = x[SAFI_LS_VPN-(72)]
	_ = x[SAFI_SR_TE_POLICY-(73)]
	_ = x[SAFI_SD_WAN_CAPABILITIES-(74)]
	_ = x[SAFI_ROUTING_POLICY-(75)]
	_ = x[SAFI_CLASSFUL_TRANSPORT-(76)]
	_ = x[SAFI_TUNNELED_FLOWSPEC-(77)]
	_ = x[SAFI_MCAST_TREE-(78)]
	_ = x[SAFI_DPS-(79)]
	_ = x[SAFI_LS_SPF-(80)]
	_ = x[SAFI_CAR-(83)]
	_ = x[SAFI_VPN_CAR-(84)]
	_ = x[SAFI_MUP-(85)]
	_ = x[SAFI_MPLS_VPN-(128)]
	_ = x[SAFI_MULTICAST_VPNS-(129)]
	_ = x[SAFI_ROUTE_TARGET-(132)]
	_ = x[SAFI_FLOWSPEC-(133)]
	_ = x[SAFI_L3VPN_FLOWSPEC-(134)]
	_ = x[SAFI_VPN_DISCOVERY-(140)]
}

var _SafiValues = []Safi{SAFI_UNICAST, SAFI_MULTICAST, SAFI_MPLS, SAFI_MCAST_VPN, SAFI_PLACEMENT_MSPW, SAFI_MCAST_VPLS, SAFI_SFC, SAFI_TUNNEL, SAFI_VPLS, SAFI_MDT, SAFI_4OVER6, SAFI_6OVER4, SAFI_L1VPN_DISCOVERY, SAFI_EVPNS, SAFI_LS, SAFI_LS_VPN, SAFI_SR_TE_POLICY, SAFI_SD_WAN_CAPABILITIES, SAFI_ROUTING_POLICY, SAFI_CLASSFUL_TRANSPORT, SAFI_TUNNELED_FLOWSPEC, SAFI_MCAST_TREE, SAFI_DPS, SAFI_LS_SPF, SAFI_CAR, SAFI_VPN_CAR, SAFI_MUP, SAFI_MPLS_VPN, SAFI_MULTICAST_VPNS, SAFI_ROUTE_TARGET, SAFI_FLOWSPEC, SAFI_L3VPN_FLOWSPEC, SAFI_VPN_DISCOVERY}

var _SafiNameToValueMap = map[string]Safi{
	_SafiName_0[0:7]:          SAFI_UNICAST,
	_SafiLowerName_0[0:7]:     SAFI_UNICAST,
	_SafiName_0[7:16]:         SAFI_MULTICAST,
	_SafiLowerName_0[7:16]:    SAFI_MULTICAST,
	_SafiName_1[0:4]:          SAFI_MPLS,
	_SafiLowerName_1[0:4]:     SAFI_MPLS,
	_SafiName_1[4:13]:         SAFI_MCAST_VPN,
	_SafiLowerName_1[4:13]:    SAFI_MCAST_VPN,
	_SafiName_1[13:27]:        SAFI_PLACEMENT_MSPW,
	_SafiLowerName_1[13:27]:   SAFI_PLACEMENT_MSPW,
	_SafiName_2[0:10]:         SAFI_MCAST_VPLS,
	_SafiLowerName_2[0:10]:    SAFI_MCAST_VPLS,
	_SafiName_2[10:13]:        SAFI_SFC,
	_SafiLowerName_2[10:13]:   SAFI_SFC,
	_SafiName_3[0:6]:          SAFI_TUNNEL,
	_SafiLowerName_3[0:6]:     SAFI_TUNNEL,
	_SafiName_3[6:10]:         SAFI_VPLS,
	_SafiLowerName_3[6:10]:    SAFI_VPLS,
	_SafiName_3[10:13]:        SAFI_MDT,
	_SafiLowerName_3[10:13]:   SAFI_MDT,
	_SafiName_3[13:19]:        SAFI_4OVER6,
	_SafiLowerName_3[13:19]:   SAFI_4OVER6,
	_SafiName_3[19:25]:        SAFI_6OVER4,
	_SafiLowerName_3[19:25]:   SAFI_6OVER4,
	_SafiName_3[25:40]:        SAFI_L1VPN_DISCOVERY,
	_SafiLowerName_3[25:40]:   SAFI_L1VPN_DISCOVERY,
	_SafiName_3[40:45]:        SAFI_EVPNS,
	_SafiLowerName_3[40:45]:   SAFI_EVPNS,
	_SafiName_3[45:47]:        SAFI_LS,
	_SafiLowerName_3[45:47]:   SAFI_LS,
	_SafiName_3[47:53]:        SAFI_LS_VPN,
	_SafiLowerName_3[47:53]:   SAFI_LS_VPN,
	_SafiName_3[53:65]:        SAFI_SR_TE_POLICY,
	_SafiLowerName_3[53:65]:   SAFI_SR_TE_POLICY,
	_SafiName_3[65:84]:        SAFI_SD_WAN_CAPABILITIES,
	_SafiLowerName_3[65:84]:   SAFI_SD_WAN_CAPABILITIES,
	_SafiName_3[84:98]:        SAFI_ROUTING_POLICY,
	_SafiLowerName_3[84:98]:   SAFI_ROUTING_POLICY,
	_SafiName_3[98:116]:       SAFI_CLASSFUL_TRANSPORT,
	_SafiLowerName_3[98:116]:  SAFI_CLASSFUL_TRANSPORT,
	_SafiName_3[116:133]:      SAFI_TUNNELED_FLOWSPEC,
	_SafiLowerName_3[116:133]: SAFI_TUNNELED_FLOWSPEC,
	_SafiName_3[133:143]:      SAFI_MCAST_TREE,
	_SafiLowerName_3[133:143]: SAFI_MCAST_TREE,
	_SafiName_3[143:146]:      SAFI_DPS,
	_SafiLowerName_3[143:146]: SAFI_DPS,
	_SafiName_3[146:152]:      SAFI_LS_SPF,
	_SafiLowerName_3[146:152]: SAFI_LS_SPF,
	_SafiName_4[0:3]:          SAFI_CAR,
	_SafiLowerName_4[0:3]:     SAFI_CAR,
	_SafiName_4[3:10]:         SAFI_VPN_CAR,
	_SafiLowerName_4[3:10]:    SAFI_VPN_CAR,
	_SafiName_4[10:13]:        SAFI_MUP,
	_SafiLowerName_4[10:13]:   SAFI_MUP,
	_SafiName_5[0:8]:          SAFI_MPLS_VPN,
	_SafiLowerName_5[0:8]:     SAFI_MPLS_VPN,
	_SafiName_5[8:22]:         SAFI_MULTICAST_VPNS,
	_SafiLowerName_5[8:22]:    SAFI_MULTICAST_VPNS,
	_SafiName_6[0:12]:         SAFI_ROUTE_TARGET,
	_SafiLowerName_6[0:12]:    SAFI_ROUTE_TARGET,
	_SafiName_6[12:20]:        SAFI_FLOWSPEC,
	_SafiLowerName_6[12:20]:   SAFI_FLOWSPEC,
	_SafiName_6[20:34]:        SAFI_L3VPN_FLOWSPEC,
	_SafiLowerName_6[20:34]:   SAFI_L3VPN_FLOWSPEC,
	_SafiName_7[0:13]:         SAFI_VPN_DISCOVERY,
	_SafiLowerName_7[0:13]:    SAFI_VPN_DISCOVERY,
}

var _SafiNames = []string{
	_SafiName_0[0:7],
	_SafiName_0[7:16],
	_SafiName_1[0:4],
	_SafiName_1[4:13],
	_SafiName_1[13:27],
	_SafiName_2[0:10],
	_SafiName_2[10:13],
	_SafiName_3[0:6],
	_SafiName_3[6:10],
	_SafiName_3[10:13],
	_SafiName_3[13:19],
	_SafiName_3[19:25],
	_SafiName_3[25:40],
	_SafiName_3[40:45],
	_SafiName_3[45:47],
	_SafiName_3[47:53],
	_SafiName_3[53:65],
	_SafiName_3[65:84],
	_SafiName_3[84:98],
	_SafiName_3[98:116],
	_SafiName_3[116:133],
	_SafiName_3[133:143],
	_SafiName_3[143:146],
	_SafiName_3[146:152],
	_SafiName_4[0:3],
	_SafiName_4[3:10],
	_SafiName_4[10:13],
	_SafiName_5[0:8],
	_SafiName_5[8:22],
	_SafiName_6[0:12],
	_SafiName_6[12:20],
	_SafiName_6[20:34],
	_SafiName_7[0:13],
}

// SafiString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SafiString(s string) (Safi, error) {
	if val, ok := _SafiNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SafiNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Safi values", s)
}

// SafiValues returns all values of the enum
func SafiValues() []Safi {
	return _SafiValues
}

// SafiStrings returns a slice of all String values of the enum
func SafiStrings() []string {
	strs := make([]string, len(_SafiNames))
	copy(strs, _SafiNames)
	return strs
}

// IsASafi returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Safi) IsASafi() bool {
	for _, v := range _SafiValues {
		if i == v {
			return true
		}
	}
	return false
}
