// Code generated by "enumer -type ExtcomType -trimprefix EXTCOM_"; DO NOT EDIT.

package attrs

import (
	"fmt"
	"strings"
)

const _ExtcomTypeName = "AS2TARGETORIGINSUBTYPEIP4IP4_TARGETIP4_ORIGINAS4AS4_TARGETAS4_ORIGINFLOW_REDIRECT_NHTRANSITIVEFLOW_RATE_BYTESFLOW_ACTIONFLOW_REDIRECT_AS2FLOW_DSCPFLOW_RATE_PACKETSFLOW_REDIRECT_IP4FLOW_REDIRECT_AS4TYPE"
const _ExtcomTypeLowerName = "as2targetoriginsubtypeip4ip4_targetip4_originas4as4_targetas4_originflow_redirect_nhtransitiveflow_rate_bytesflow_actionflow_redirect_as2flow_dscpflow_rate_packetsflow_redirect_ip4flow_redirect_as4type"

var _ExtcomTypeMap = map[ExtcomType]string{
	0:     _ExtcomTypeName[0:3],
	2:     _ExtcomTypeName[3:9],
	3:     _ExtcomTypeName[9:15],
	255:   _ExtcomTypeName[15:22],
	256:   _ExtcomTypeName[22:25],
	258:   _ExtcomTypeName[25:35],
	259:   _ExtcomTypeName[35:45],
	512:   _ExtcomTypeName[45:48],
	514:   _ExtcomTypeName[48:58],
	515:   _ExtcomTypeName[58:68],
	2048:  _ExtcomTypeName[68:84],
	16384: _ExtcomTypeName[84:94],
	32774: _ExtcomTypeName[94:109],
	32775: _ExtcomTypeName[109:120],
	32776: _ExtcomTypeName[120:137],
	32777: _ExtcomTypeName[137:146],
	32780: _ExtcomTypeName[146:163],
	33032: _ExtcomTypeName[163:180],
	33288: _ExtcomTypeName[180:197],
	48896: _ExtcomTypeName[197:201],
}

func (i ExtcomType) String() string {
	if str, ok := _ExtcomTypeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ExtcomType(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ExtcomTypeNoOp() {
	var x [1]struct{}
	_ = x[EXTCOM_AS2-(0)]
	_ = x[EXTCOM_TARGET-(2)]
	_ = x[EXTCOM_ORIGIN-(3)]
	_ = x[EXTCOM_SUBTYPE-(255)]
	_ = x[EXTCOM_IP4-(256)]
	_ = x[EXTCOM_IP4_TARGET-(258)]
	_ = x[EXTCOM_IP4_ORIGIN-(259)]
	_ = x[EXTCOM_AS4-(512)]
	_ = x[EXTCOM_AS4_TARGET-(514)]
	_ = x[EXTCOM_AS4_ORIGIN-(515)]
	_ = x[EXTCOM_FLOW_REDIRECT_NH-(2048)]
	_ = x[EXTCOM_TRANSITIVE-(16384)]
	_ = x[EXTCOM_FLOW_RATE_BYTES-(32774)]
	_ = x[EXTCOM_FLOW_ACTION-(32775)]
	_ = x[EXTCOM_FLOW_REDIRECT_AS2-(32776)]
	_ = x[EXTCOM_FLOW_DSCP-(32777)]
	_ = x[EXTCOM_FLOW_RATE_PACKETS-(32780)]
	_ = x[EXTCOM_FLOW_REDIRECT_IP4-(33032)]
	_ = x[EXTCOM_FLOW_REDIRECT_AS4-(33288)]
	_ = x[EXTCOM_TYPE-(48896)]
}

var _ExtcomTypeValues = []ExtcomType{EXTCOM_AS2, EXTCOM_TARGET, EXTCOM_ORIGIN, EXTCOM_SUBTYPE, EXTCOM_IP4, EXTCOM_IP4_TARGET, EXTCOM_IP4_ORIGIN, EXTCOM_AS4, EXTCOM_AS4_TARGET, EXTCOM_AS4_ORIGIN, EXTCOM_FLOW_REDIRECT_NH, EXTCOM_TRANSITIVE, EXTCOM_FLOW_RATE_BYTES, EXTCOM_FLOW_ACTION, EXTCOM_FLOW_REDIRECT_AS2, EXTCOM_FLOW_DSCP, EXTCOM_FLOW_RATE_PACKETS, EXTCOM_FLOW_REDIRECT_IP4, EXTCOM_FLOW_REDIRECT_AS4, EXTCOM_TYPE}

var _ExtcomTypeNameToValueMap = map[string]ExtcomType{
	_ExtcomTypeName[0:3]:          EXTCOM_AS2,
	_ExtcomTypeLowerName[0:3]:     EXTCOM_AS2,
	_ExtcomTypeName[3:9]:          EXTCOM_TARGET,
	_ExtcomTypeLowerName[3:9]:     EXTCOM_TARGET,
	_ExtcomTypeName[9:15]:         EXTCOM_ORIGIN,
	_ExtcomTypeLowerName[9:15]:    EXTCOM_ORIGIN,
	_ExtcomTypeName[15:22]:        EXTCOM_SUBTYPE,
	_ExtcomTypeLowerName[15:22]:   EXTCOM_SUBTYPE,
	_ExtcomTypeName[22:25]:        EXTCOM_IP4,
	_ExtcomTypeLowerName[22:25]:   EXTCOM_IP4,
	_ExtcomTypeName[25:35]:        EXTCOM_IP4_TARGET,
	_ExtcomTypeLowerName[25:35]:   EXTCOM_IP4_TARGET,
	_ExtcomTypeName[35:45]:        EXTCOM_IP4_ORIGIN,
	_ExtcomTypeLowerName[35:45]:   EXTCOM_IP4_ORIGIN,
	_ExtcomTypeName[45:48]:        EXTCOM_AS4,
	_ExtcomTypeLowerName[45:48]:   EXTCOM_AS4,
	_ExtcomTypeName[48:58]:        EXTCOM_AS4_TARGET,
	_ExtcomTypeLowerName[48:58]:   EXTCOM_AS4_TARGET,
	_ExtcomTypeName[58:68]:        EXTCOM_AS4_ORIGIN,
	_ExtcomTypeLowerName[58:68]:   EXTCOM_AS4_ORIGIN,
	_ExtcomTypeName[68:84]:        EXTCOM_FLOW_REDIRECT_NH,
	_ExtcomTypeLowerName[68:84]:   EXTCOM_FLOW_REDIRECT_NH,
	_ExtcomTypeName[84:94]:        EXTCOM_TRANSITIVE,
	_ExtcomTypeLowerName[84:94]:   EXTCOM_TRANSITIVE,
	_ExtcomTypeName[94:109]:       EXTCOM_FLOW_RATE_BYTES,
	_ExtcomTypeLowerName[94:109]:  EXTCOM_FLOW_RATE_BYTES,
	_ExtcomTypeName[109:120]:      EXTCOM_FLOW_ACTION,
	_ExtcomTypeLowerName[109:120]: EXTCOM_FLOW_ACTION,
	_ExtcomTypeName[120:137]:      EXTCOM_FLOW_REDIRECT_AS2,
	_ExtcomTypeLowerName[120:137]: EXTCOM_FLOW_REDIRECT_AS2,
	_ExtcomTypeName[137:146]:      EXTCOM_FLOW_DSCP,
	_ExtcomTypeLowerName[137:146]: EXTCOM_FLOW_DSCP,
	_ExtcomTypeName[146:163]:      EXTCOM_FLOW_RATE_PACKETS,
	_ExtcomTypeLowerName[146:163]: EXTCOM_FLOW_RATE_PACKETS,
	_ExtcomTypeName[163:180]:      EXTCOM_FLOW_REDIRECT_IP4,
	_ExtcomTypeLowerName[163:180]: EXTCOM_FLOW_REDIRECT_IP4,
	_ExtcomTypeName[180:197]:      EXTCOM_FLOW_REDIRECT_AS4,
	_ExtcomTypeLowerName[180:197]: EXTCOM_FLOW_REDIRECT_AS4,
	_ExtcomTypeName[197:201]:      EXTCOM_TYPE,
	_ExtcomTypeLowerName[197:201]: EXTCOM_TYPE,
}

var _ExtcomTypeNames = []string{
	_ExtcomTypeName[0:3],
	_ExtcomTypeName[3:9],
	_ExtcomTypeName[9:15],
	_ExtcomTypeName[15:22],
	_ExtcomTypeName[22:25],
	_ExtcomTypeName[25:35],
	_ExtcomTypeName[35:45],
	_ExtcomTypeName[45:48],
	_ExtcomTypeName[48:58],
	_ExtcomTypeName[58:68],
	_ExtcomTypeName[68:84],
	_ExtcomTypeName[84:94],
	_ExtcomTypeName[94:109],
	_ExtcomTypeName[109:120],
	_ExtcomTypeName[120:137],
	_ExtcomTypeName[137:146],
	_ExtcomTypeName[146:163],
	_ExtcomTypeName[163:180],
	_ExtcomTypeName[180:197],
	_ExtcomTypeName[197:201],
}

// ExtcomTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ExtcomTypeString(s string) (ExtcomType, error) {
	if val, ok := _ExtcomTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ExtcomTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ExtcomType values", s)
}

// ExtcomTypeValues returns all values of the enum
func ExtcomTypeValues() []ExtcomType {
	return _ExtcomTypeValues
}

// ExtcomTypeStrings returns a slice of all String values of the enum
func ExtcomTypeStrings() []string {
	strs := make([]string, len(_ExtcomTypeNames))
	copy(strs, _ExtcomTypeNames)
	return strs
}

// IsAExtcomType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ExtcomType) IsAExtcomType() bool {
	_, ok := _ExtcomTypeMap[i]
	return ok
}
