// Code generated by "enumer -type AFI -trimprefix AFI_"; DO NOT EDIT.

package af

import (
	"fmt"
	"strings"
)

const (
	_AFIName_0      = "INVALIDIPV4IPV6"
	_AFILowerName_0 = "invalidipv4ipv6"
	_AFIName_1      = "L2VPNMPLS_SECTIONMPLS_LSPMPLS_PSEUDOWIREMT_IPV4MT_IPV6SFC"
	_AFILowerName_1 = "l2vpnmpls_sectionmpls_lspmpls_pseudowiremt_ipv4mt_ipv6sfc"
	_AFIName_2      = "LS"
	_AFILowerName_2 = "ls"
	_AFIName_3      = "ROUTING_POLICYMPLS_NAMESPACES"
	_AFILowerName_3 = "routing_policympls_namespaces"
)

var (
	_AFIIndex_0 = [...]uint8{0, 7, 11, 15}
	_AFIIndex_1 = [...]uint8{0, 5, 17, 25, 40, 47, 54, 57}
	_AFIIndex_2 = [...]uint8{0, 2}
	_AFIIndex_3 = [...]uint8{0, 14, 29}
)

func (i AFI) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _AFIName_0[_AFIIndex_0[i]:_AFIIndex_0[i+1]]
	case 25 <= i && i <= 31:
		i -= 25
		return _AFIName_1[_AFIIndex_1[i]:_AFIIndex_1[i+1]]
	case i == 16388:
		return _AFIName_2
	case 16398 <= i && i <= 16399:
		i -= 16398
		return _AFIName_3[_AFIIndex_3[i]:_AFIIndex_3[i+1]]
	default:
		return fmt.Sprintf("AFI(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AFINoOp() {
	var x [1]struct{}
	_ = x[AFI_INVALID-(0)]
	_ = x[AFI_IPV4-(1)]
	_ = x[AFI_IPV6-(2)]
	_ = x[AFI_L2VPN-(25)]
	_ = x[AFI_MPLS_SECTION-(26)]
	_ = x[AFI_MPLS_LSP-(27)]
	_ = x[AFI_MPLS_PSEUDOWIRE-(28)]
	_ = x[AFI_MT_IPV4-(29)]
	_ = x[AFI_MT_IPV6-(30)]
	_ = x[AFI_SFC-(31)]
	_ = x[AFI_LS-(16388)]
	_ = x[AFI_ROUTING_POLICY-(16398)]
	_ = x[AFI_MPLS_NAMESPACES-(16399)]
}

var _AFIValues = []AFI{AFI_INVALID, AFI_IPV4, AFI_IPV6, AFI_L2VPN, AFI_MPLS_SECTION, AFI_MPLS_LSP, AFI_MPLS_PSEUDOWIRE, AFI_MT_IPV4, AFI_MT_IPV6, AFI_SFC, AFI_LS, AFI_ROUTING_POLICY, AFI_MPLS_NAMESPACES}

var _AFINameToValueMap = map[string]AFI{
	_AFIName_0[0:7]:        AFI_INVALID,
	_AFILowerName_0[0:7]:   AFI_INVALID,
	_AFIName_0[7:11]:       AFI_IPV4,
	_AFILowerName_0[7:11]:  AFI_IPV4,
	_AFIName_0[11:15]:      AFI_IPV6,
	_AFILowerName_0[11:15]: AFI_IPV6,
	_AFIName_1[0:5]:        AFI_L2VPN,
	_AFILowerName_1[0:5]:   AFI_L2VPN,
	_AFIName_1[5:17]:       AFI_MPLS_SECTION,
	_AFILowerName_1[5:17]:  AFI_MPLS_SECTION,
	_AFIName_1[17:25]:      AFI_MPLS_LSP,
	_AFILowerName_1[17:25]: AFI_MPLS_LSP,
	_AFIName_1[25:40]:      AFI_MPLS_PSEUDOWIRE,
	_AFILowerName_1[25:40]: AFI_MPLS_PSEUDOWIRE,
	_AFIName_1[40:47]:      AFI_MT_IPV4,
	_AFILowerName_1[40:47]: AFI_MT_IPV4,
	_AFIName_1[47:54]:      AFI_MT_IPV6,
	_AFILowerName_1[47:54]: AFI_MT_IPV6,
	_AFIName_1[54:57]:      AFI_SFC,
	_AFILowerName_1[54:57]: AFI_SFC,
	_AFIName_2[0:2]:        AFI_LS,
	_AFILowerName_2[0:2]:   AFI_LS,
	_AFIName_3[0:14]:       AFI_ROUTING_POLICY,
	_AFILowerName_3[0:14]:  AFI_ROUTING_POLICY,
	_AFIName_3[14:29]:      AFI_MPLS_NAMESPACES,
	_AFILowerName_3[14:29]: AFI_MPLS_NAMESPACES,
}

var _AFINames = []string{
	_AFIName_0[0:7],
	_AFIName_0[7:11],
	_AFIName_0[11:15],
	_AFIName_1[0:5],
	_AFIName_1[5:17],
	_AFIName_1[17:25],
	_AFIName_1[25:40],
	_AFIName_1[40:47],
	_AFIName_1[47:54],
	_AFIName_1[54:57],
	_AFIName_2[0:2],
	_AFIName_3[0:14],
	_AFIName_3[14:29],
}

// AFIString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AFIString(s string) (AFI, error) {
	if val, ok := _AFINameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AFINameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AFI values", s)
}

// AFIValues returns all values of the enum
func AFIValues() []AFI {
	return _AFIValues
}

// AFIStrings returns a slice of all String values of the enum
func AFIStrings() []string {
	strs := make([]string, len(_AFINames))
	copy(strs, _AFINames)
	return strs
}

// IsAAFI returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AFI) IsAAFI() bool {
	for _, v := range _AFIValues {
		if i == v {
			return true
		}
	}
	return false
}
